name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Test package ntp
        run: go test -v ./internal/ntp...

      - name: Test package server
        run: go test -v ./internal/server

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with tag ${{ github.ref_name }}
        run: |
          docker build --build-arg version=${{ github.ref_name }} \
            --tag ghcr.io/donsprallo/gots:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push ghcr.io/donsprallo/${{ github.ref_name }}
