name: UnitTest

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Test package ntp
        run: go test -v ./internal/ntp...

      - name: Test package server
        run: go test -v ./internal/server

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with tag latest
        run: |
          docker build --build-arg version=latest \
            --tag ghcr.io/donsprallo/gots:latest .

      - name: Push Docker image
        run: docker push ghcr.io/donsprallo/gots
